---
abstract: 'Kirinki environment manager.'
author:
  - 'Pablo Alvarez de Sotomayor Posadillo <palvarez@ritho.net>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.4004'
  Module::Signature: '0.83'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: kirinki-env
provides:
  kirinki::env:
    file: lib/kirinki/env.pm
    version: '0.03'
  kirinki::env::config:
    file: lib/kirinki/env/config.pm
    version: '0.02'
  kirinki::git:
    file: lib/kirinki/git.pm
    version: '0.01'
requires:
  Config::Tiny: '2.24'
  MIME::Base64: '3.15'
  Switch: '2.17'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
