name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.30'
    - name: Requirements
      run: cpanm --installdeps .
    - name: Build
      run: |
        perl Build.PL
        ./Build
    - name: Test
      run: ./Build test
    - name: install
      run: ./Build install
    - name: Prove
      run: prove -lv t
