name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Requirements
      run: |
        cpan -i Module::Build
    - name: Build
      run: |
        perl Build.PL
        ./Build
    - name: Test
      run: ./Build test
    - name: install
      run: ./Build install
