name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.30'
    - name: Requirements
      run: cpanm --installdeps .
    - name: Build
      run: |
        perl Build.PL
        ./Build
    - name: Test
      run: ./Build test
    - name: Prove
      run: prove -lv t
    - name: Test All
      run: ./Build testall
    - name: install
      run: ./Build install
    - name: Dist Test
      run: ./Build disttest
    - name: Dist Build
      run: ./Build dist
    - name: Dist Sign
      run: ./Build distsign
    - name: Test coverage
      run: |
        ./Build testcover
        cover | grep Total | awk -F ' ' '{print $2}' | xargs perl -e 'if ($ARGV[0] < 60) { print "Statement coverage is " . $ARGV[0] ; } else { print "0"; }' | xargs -I % bash -c 'if [ "0" != "%" ]; then echo "%"; exit -1; fi'
        cover | grep Total | awk -F ' ' '{print $3}' | xargs perl -e 'if ($ARGV[0] < 50) { print "Branch coverage is " . $ARGV[0] ; } else { print "0"; }' | xargs -I % bash -c 'if [ "0" != "%" ]; then echo "%"; exit -1; fi'
        cover | grep Total | awk -F ' ' '{print $4}' | xargs perl -e 'if ($ARGV[0] < 50) { print "Condition coverage is " . $ARGV[0] ; } else { print "0"; }' | xargs -I % bash -c 'if [ "0" != "%" ]; then echo "%"; exit -1; fi'
        cover | grep Total | awk -F ' ' '{print $5}' | xargs perl -e 'if ($ARGV[0] < 80) { print "Function coverage is " . $ARGV[0] ; } else { print "0"; }' | xargs -I % bash -c 'if [ "0" != "%" ]; then echo "%"; exit -1; fi'
        cover | grep Total | awk -F ' ' '{print $8}' | xargs perl -e 'if ($ARGV[0] < 60) { print "Total coverage is " . $ARGV[0] ; } else { print "0"; }' | xargs -I % bash -c 'if [ "0" != "%" ]; then echo "%"; exit -1; fi'
